package com.producto4.model.entidades;
// Generated 26-dic-2021 21:27:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede  implements java.io.Serializable {


     private short id;
     private String ubicacion;
     private String tipo;
     private Set usuariosProyectoses = new HashSet(0);

    public Sede() {
    }

	
    public Sede(short id, String ubicacion, String tipo) {
        this.id = id;
        this.ubicacion = ubicacion;
        this.tipo = tipo;
    }
    public Sede(short id, String ubicacion, String tipo, Set usuariosProyectoses) {
       this.id = id;
       this.ubicacion = ubicacion;
       this.tipo = tipo;
       this.usuariosProyectoses = usuariosProyectoses;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuariosProyectoses() {
        return this.usuariosProyectoses;
    }
    
    public void setUsuariosProyectoses(Set usuariosProyectoses) {
        this.usuariosProyectoses = usuariosProyectoses;
    }




}


