package com.producto4.model.entidades;
// Generated 26-dic-2021 21:27:55 by Hibernate Tools 4.3.1



/**
 * UsuariosSedes generated by hbm2java
 */
public class UsuariosSedes  implements java.io.Serializable {


     private short id;
     private Usuario usuario;
     private short idSede;

    public UsuariosSedes() {
    }

    public UsuariosSedes(short id, Usuario usuario, short idSede) {
       this.id = id;
       this.usuario = usuario;
       this.idSede = idSede;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public short getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(short idSede) {
        this.idSede = idSede;
    }




}


