package com.producto4.model.entidades;
// Generated 26-dic-2021 21:27:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private short id;
     private String password;
     private short administrador;
     private String dni;
     private String nombre;
     private String apellido;
     private String correo;
     private Date fechaNacimiento;
     private String usuario;
     private String puesto;
     private short idSede;
     private String tipoEmpleado;
     private Float salario;
     private String territorio;
     private Set usuariosSedeses = new HashSet(0);
     private Set usuariosProyectoses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(short id, String password, short administrador, String dni, String nombre, String apellido, String correo, Date fechaNacimiento, String usuario, String puesto, short idSede, String tipoEmpleado) {
        this.id = id;
        this.password= password;
        this.administrador = administrador;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido = apellido;
        this.correo = correo;
        this.fechaNacimiento = fechaNacimiento;
        this.usuario = usuario;
        this.puesto = puesto;
        this.idSede = idSede;
        this.tipoEmpleado = tipoEmpleado;
    }
    public Usuario(short id, String password,short administrador, String dni, String nombre, String apellido, String correo, Date fechaNacimiento, String usuario, String puesto, short idSede, String tipoEmpleado, Float salario, String territorio, Set usuariosSedeses, Set usuariosProyectoses) {
       this.id = id;
       this.password= password;
       this.administrador = administrador;
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.fechaNacimiento = fechaNacimiento;
       this.usuario = usuario;
       this.puesto = puesto;
       this.idSede = idSede;
       this.tipoEmpleado = tipoEmpleado;
       this.salario = salario;
       this.territorio = territorio;
       this.usuariosSedeses = usuariosSedeses;
       this.usuariosProyectoses = usuariosProyectoses;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public short getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(short administrador) {
        this.administrador = administrador;
    }
    
     public String getPassword() {
        return this.password;
    }
     
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public short getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(short idSede) {
        this.idSede = idSede;
    }
    public String getTipoEmpleado() {
        return this.tipoEmpleado;
    }
    
    public void setTipoEmpleado(String tipoEmpleado) {
        this.tipoEmpleado = tipoEmpleado;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public String getTerritorio() {
        return this.territorio;
    }
    
    public void setTerritorio(String territorio) {
        this.territorio = territorio;
    }
    public Set getUsuariosSedeses() {
        return this.usuariosSedeses;
    }
    
    public void setUsuariosSedeses(Set usuariosSedeses) {
        this.usuariosSedeses = usuariosSedeses;
    }
    public Set getUsuariosProyectoses() {
        return this.usuariosProyectoses;
    }
    
    public void setUsuariosProyectoses(Set usuariosProyectoses) {
        this.usuariosProyectoses = usuariosProyectoses;
    }




}


